kata:
    path:     /
    defaults: { _controller: "AppBundle:Kata:index" }

kata_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Kata:show" }

kata_new:
    path:     /new
    defaults: { _controller: "AppBundle:Kata:new" }

kata_create:
    path:     /create
    defaults: { _controller: "AppBundle:Kata:create" }
    methods:  POST

kata_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Kata:edit" }

kata_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Kata:update" }
    methods:  [POST, PUT]

kata_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Kata:delete" }
    methods:  [POST, DELETE]
