<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KataRepository extends EntityRepository
{
}
